server:
  DBpath: "mysql+mysqlconnector://sline:sline@localhost/slineDB"
  DBname: slineDB
  DBuser: sline
  DBpasswd: sline
  ImgPath: './static/img'

  sphinxSearchServer: '127.0.0.1'
  sphinxSearchPort: 9312